name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world: #Nombre de la chamba
    runs-on: ubuntu-latest # El sistema operativo sobre el cual se llevará el workflow
    
    steps:
      - name: Echo the message #Nombre del paso
        run: |    
          echo "Hola midu!"
      - name: Dime la fecha
        run: date
      - run: ls -l